# Loki Configuration for Manufacturing Analytics
# AGPL v3 Licensed - Consider compliance for SaaS usage

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Manufacturing-specific log retention
limits_config:
  retention_period: 30d  # Keep logs for 30 days
  ingestion_rate_mb: 16  # Allow higher ingestion for manufacturing data
  ingestion_burst_size_mb: 32
  max_query_series: 500
  max_streams_per_user: 10000

# Ruler for alerting on logs
ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true

# Analytics and usage
analytics:
  reporting_enabled: false

# Manufacturing log parsing
chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 30d