version: '3.8'

# Secure Docker Compose Configuration
# Uses environment variables for all sensitive values

services:
  # TimescaleDB with secure configuration
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: manufacturing-timescaledb-secure
    environment:
      # Password from environment or .env file
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-manufacturing}
      # Security settings
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=trust"
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./prisma/migrations/simplify-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - manufacturing-net

  # Ollama for local AI
  ollama:
    image: ollama/ollama:latest
    container_name: manufacturing-ollama-secure
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=${OLLAMA_MODELS:-/root/.ollama/models}
      - OLLAMA_NUM_PARALLEL=${OLLAMA_NUM_PARALLEL:-1}
      - OLLAMA_MAX_LOADED_MODELS=${OLLAMA_MAX_LOADED_MODELS:-1}
    deploy:
      resources:
        limits:
          memory: ${OLLAMA_MEMORY_LIMIT:-4g}
    restart: unless-stopped
    networks:
      - manufacturing-net

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: manufacturing-redis-secure
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --maxmemory ${REDIS_MAX_MEMORY:-512mb}
      --maxmemory-policy allkeys-lru
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - manufacturing-net

volumes:
  timescale_data:
    driver: local
  ollama_data:
    driver: local
  redis_data:
    driver: local

networks:
  manufacturing-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16