apiVersion: v2
name: manufacturing-analytics
description: A production-ready Manufacturing Analytics Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - manufacturing
  - analytics
  - iot
  - monitoring
  - nextjs
home: https://github.com/your-org/manufacturing-analytics-platform
sources:
  - https://github.com/your-org/manufacturing-analytics-platform
maintainers:
  - name: Platform Team
    email: platform@your-org.com
dependencies:
  - name: postgresql
    version: 13.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: 19.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled