global:
  # Global configuration
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@manufacturing.company.com'
  smtp_auth_username: 'alerts@manufacturing.company.com'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true
  
  # Slack configuration
  slack_api_url: '${SLACK_WEBHOOK_URL}'
  
  # PagerDuty configuration  
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree for alert routing
route:
  group_by: ['alertname', 'severity', 'category']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default-receiver'
  
  # Routing rules
  routes:
    # Critical manufacturing alerts - immediate escalation
    - match:
        severity: critical
        category: manufacturing
      receiver: 'manufacturing-critical'
      group_wait: 0s
      group_interval: 1m
      repeat_interval: 5m
      continue: true
    
    # Manufacturing warnings
    - match:
        severity: warning
        category: manufacturing
      receiver: 'manufacturing-warnings'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 2h
    
    # Infrastructure critical alerts
    - match:
        severity: critical
        category: infrastructure
      receiver: 'infrastructure-critical'
      group_wait: 0s
      group_interval: 2m
      repeat_interval: 10m
      continue: true
    
    # Application alerts
    - match:
        category: application
      receiver: 'application-team'
      group_wait: 1m
      group_interval: 5m
      repeat_interval: 4h
    
    # Security alerts - immediate escalation
    - match:
        category: security
      receiver: 'security-team'
      group_wait: 0s
      group_interval: 1m
      repeat_interval: 1h
      continue: true
    
    # Database alerts
    - match:
        component: database
      receiver: 'database-team'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 2h
    
    # OEE and production alerts during business hours
    - match:
        component: oee
      receiver: 'production-team'
      group_wait: 1m
      group_interval: 5m
      repeat_interval: 1h
      active_time_intervals:
        - business-hours
    
    # Quality alerts - always active
    - match:
        component: quality
      receiver: 'quality-team'
      group_wait: 30s
      group_interval: 2m
      repeat_interval: 30m

# Inhibition rules to prevent alert spam
inhibit_rules:
  # Infrastructure alerts inhibit application alerts
  - source_matchers:
      - alertname = "Equipment_Availability_Critical"
    target_matchers:
      - component = "performance"
    equal: ['instance', 'work_unit_id']

  # Critical alerts inhibit warning alerts for same component
  - source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
    equal: ['alertname', 'instance', 'work_unit_id']

  # Production stopped inhibits other production alerts
  - source_matchers:
      - alertname = "Production_Stopped"
    target_matchers:
      - component = "production_target"
      - component = "cycle_time"
    equal: ['instance', 'work_unit_id']

# Time intervals for routing
time_intervals:
  - name: business-hours
    time_intervals:
      - times:
          - start_time: '08:00'
            end_time: '18:00'
        weekdays: ['monday:friday']
        location: 'America/New_York'

  - name: after-hours
    time_intervals:
      - times:
          - start_time: '18:01'
            end_time: '07:59'
        weekdays: ['monday:friday']
        location: 'America/New_York'
      - weekdays: ['saturday', 'sunday']
        location: 'America/New_York'

# Receivers for different alert types
receivers:
  # Default receiver
  - name: 'default-receiver'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#manufacturing-alerts'
        title: 'Manufacturing Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Instance:* {{ .Labels.instance }}
          {{ end }}

  # Manufacturing critical alerts
  - name: 'manufacturing-critical'
    email_configs:
      - to: 'manufacturing-team@company.com,operations-manager@company.com'
        subject: '🚨 CRITICAL Manufacturing Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          CRITICAL MANUFACTURING ALERT
          
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Equipment: {{ .Labels.equipment }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          
          {{ if .Annotations.runbook_url }}
          Runbook: {{ .Annotations.runbook_url }}
          {{ end }}
          
          View in manufacturingPlatform: http://manufacturingPlatform:3000/d/manufacturing-overview
          {{ end }}
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#manufacturing-critical'
        title: '🚨 CRITICAL Manufacturing Alert'
        color: 'danger'
        text: |
          {{ range .Alerts }}
          *Equipment:* {{ .Labels.equipment }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Time:* {{ .StartsAt.Format "15:04:05" }}
          {{ if .Annotations.runbook_url }}
          *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}
          {{ end }}
    
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_MANUFACTURING_KEY}'
        description: 'Critical Manufacturing Alert: {{ .GroupLabels.alertname }}'
        severity: 'critical'
        details:
          equipment: '{{ .CommonLabels.equipment }}'
          alert_name: '{{ .CommonLabels.alertname }}'
          description: '{{ .CommonAnnotations.description }}'

  # Manufacturing warnings
  - name: 'manufacturing-warnings'
    email_configs:
      - to: 'manufacturing-team@company.com'
        subject: '⚠️ Manufacturing Warning: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          MANUFACTURING WARNING
          
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Equipment: {{ .Labels.equipment }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#manufacturing-warnings'
        title: '⚠️ Manufacturing Warning'
        color: 'warning'
        text: |
          {{ range .Alerts }}
          *Equipment:* {{ .Labels.equipment }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}

  # Infrastructure critical alerts
  - name: 'infrastructure-critical'
    email_configs:
      - to: 'infrastructure-team@company.com,sre-team@company.com'
        subject: '🔥 CRITICAL Infrastructure Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          CRITICAL INFRASTRUCTURE ALERT
          
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#infrastructure-alerts'
        title: '🔥 CRITICAL Infrastructure Alert'
        color: 'danger'
        text: |
          {{ range .Alerts }}
          *Instance:* {{ .Labels.instance }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}

  # Application team alerts
  - name: 'application-team'
    email_configs:
      - to: 'development-team@company.com'
        subject: 'Application Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          APPLICATION ALERT
          
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Component: {{ .Labels.component }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#application-alerts'
        title: 'Application Alert'
        color: 'warning'
        text: |
          {{ range .Alerts }}
          *Component:* {{ .Labels.component }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}

  # Security team alerts
  - name: 'security-team'
    email_configs:
      - to: 'security-team@company.com,ciso@company.com'
        subject: '🛡️ SECURITY Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          SECURITY ALERT
          
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          
          Immediate investigation required.
          {{ end }}
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#security-alerts'
        title: '🛡️ SECURITY Alert'
        color: 'danger'
        text: |
          {{ range .Alerts }}
          *SECURITY ALERT*
          *Instance:* {{ .Labels.instance }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Action Required:* Immediate investigation
          {{ end }}

  # Database team alerts
  - name: 'database-team'
    email_configs:
      - to: 'database-team@company.com'
        subject: 'Database Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          DATABASE ALERT
          
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Database: {{ .Labels.database }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  # Production team alerts
  - name: 'production-team'
    email_configs:
      - to: 'production-team@company.com'
        subject: 'Production Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          PRODUCTION ALERT
          
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Equipment: {{ .Labels.equipment }}
          OEE Impact: Potential impact on OEE metrics
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  # Quality team alerts
  - name: 'quality-team'
    email_configs:
      - to: 'quality-team@company.com'
        subject: 'Quality Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          QUALITY ALERT
          
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Equipment: {{ .Labels.equipment }}
          Quality Impact: {{ .Annotations.description }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          
          Immediate quality review may be required.
          {{ end }}
    
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#quality-alerts'
        title: 'Quality Alert'
        color: 'warning'
        text: |
          {{ range .Alerts }}
          *Equipment:* {{ .Labels.equipment }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Action:* Quality review required
          {{ end }}