version: '3.8'

services:
  # Optimized Ollama for low-resource systems
  ollama-optimized:
    image: ollama/ollama:latest
    container_name: manufacturing-ollama-optimized
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./scripts/ollama:/scripts
    environment:
      # Performance optimization for limited resources
      - OLLAMA_KEEP_ALIVE=5m           # Unload models after 5 minutes
      - OLLAMA_NUM_PARALLEL=1          # Only 1 request at a time
      - OLLAMA_MAX_LOADED_MODELS=1     # Only keep 1 model in memory
      - OLLAMA_DEBUG=false
      - OLLAMA_FLASH_ATTENTION=false   # Disable flash attention (saves memory)
      - OLLAMA_MAX_VRAM=0              # Force CPU-only mode
      # Model settings
      - OLLAMA_DEFAULT_MODEL=gemma:2b
      # Memory settings
      - OLLAMA_MEM_BALLAST=1073741824  # 1GB memory ballast
      - GOGC=80                        # More aggressive garbage collection
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g                   # Strict 4GB limit
          cpus: '2.0'                 # Limit to 2 CPU cores
        reservations:
          memory: 2g                   # Minimum 2GB
    networks:
      - manufacturing-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/api/tags || exit 1"]
      interval: 60s                    # Less frequent checks
      timeout: 10s
      retries: 3
      start_period: 60s
    # Custom entrypoint for optimization
    entrypoint: ["/bin/bash", "-c", "
      # Set system optimizations
      export GOMAXPROCS=2 &&
      export OLLAMA_RUNNER_THREADS=2 &&
      export OLLAMA_PARALLEL_THREADS=1 &&
      # Start Ollama
      ollama serve &
      sleep 15 &&
      # Pull and optimize Gemma:2B
      ollama pull gemma:2b &&
      # Create optimized model
      echo 'FROM gemma:2b
      PARAMETER num_thread 2
      PARAMETER num_gpu 0
      PARAMETER num_ctx 2048
      PARAMETER num_batch 256
      PARAMETER repeat_penalty 1.2
      PARAMETER temperature 0.7
      PARAMETER top_k 40
      PARAMETER top_p 0.9
      SYSTEM \"You are a helpful manufacturing assistant. Keep responses concise and focused.\"' > /tmp/optimized-gemma &&
      ollama create optimized-gemma -f /tmp/optimized-gemma &&
      echo 'Ollama optimized and ready' &&
      tail -f /dev/null
    "]

volumes:
  ollama-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./ollama-data  # Local directory for easier management

networks:
  manufacturing-network:
    external: true
    name: manufacturing-network