apiVersion: v1
kind: ConfigMap
metadata:
  name: manufacturing-analytics-config
data:
  # Non-sensitive configuration
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://manufacturing.example.com/api"
  NEXT_PUBLIC_WS_URL: "wss://manufacturing.example.com"
  
  # Feature flags
  ENABLE_TRACING: "true"
  ENABLE_METRICS: "true"
  
  # Rate limiting
  RATE_LIMIT_WINDOW_MS: "60000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  
  # Memory management
  MEMORY_RETENTION_DAYS: "30"
  CRON_SCHEDULE: "0 2 * * *"
  
  # CORS
  CORS_ALLOWED_ORIGINS: "https://manufacturing.example.com,https://app.manufacturing.example.com"